### ISSUE TITLE
Cannot find the Stata Enhanced in the searching results of package control

### ISSUE THREAD

**Issue by zlqs1985** [andrewheiss/SublimeStataEnhanced#21]
Hi, when I tried to install the Stata Enhanced plugin using package control, I didn't find it in the searching results, actually there is no such plugin which includes the "stata" keyword. When I try to install the plugin mutually, I was confused that I can't find the path "~/Library/Application Support/Sublime Text 2/Packages" in my computer, I believe it's not the default install folder of sublime am I right? In the folder where sublime text 2 was installed,I only find folder named "Pristine Packages"and it contains all sublime built-in packages. So how and where can I install this plugin correctly? I'm appreciate if you can give me some clue,thanks.

**Comment by andrewheiss** [comment]
It should be in the Package Control list (it's listed on their website at https://packagecontrol.io/packages/Stata%20Enhanced). Perhaps try reinstalling Package Control?
