### ISSUE TITLE
Set working directory

### ISSUE THREAD

**Issue by psychstatistics** [andrewheiss/SublimeStataEnhanced#25]
Thanks for creating this plug-in. This is more of a feature request than an issue.

I have been using Stata's project manager, but I like being able to work with Stata from within Sublime Text. Wondering if you have any ideas regarding how to set the working directly automatically. For example, if I double click on a Stata Project file, it will set my working directory automatically so I don't have to worry about setting the working directory each time. This makes projects super portable and immune to changes in directory structure. RStudio does this as well with their project files.

I wondering if there would be a way to send a command from Sublime Text to Stata that would allow me to set the working directory. It could be part of the execute command or something you do manually when you open up a project in sublime text.

Thoughts? I'd be happy to contribute and help out. I've never written a script like this before, so not sure how to dig in and help at this point. I am on Mac 10.10 and Stata 13.

**Comment by NilsEnevoldsen** [comment]
This does not directly address your problem, but look into -[project](https://ideas.repec.org/c/boc/bocode/s457685.html)-. Among other things, it automatically sets working directories to the do-file directory. It's the sort of package that you use completely if you use it at all, but I like its features.

**Comment by andrewheiss** [comment]
This is probably best handled with -project-, mentioned above. For now, all this ST plugin does is send commands to Stata, and for versions 11-12, it actually runs those commands from a temporary file that's not necessarily in the project root.
