### ISSUE TITLE
More than 263 lines

### ISSUE THREAD

**Issue by leoshibata** [andrewheiss/SublimeStataEnhanced#31]
I am not being able to send Stata more than 263 lines of code at a time.

I am using Mac OS X Yosemite and Stata/IC 13.1

Cheers!

**Comment by andrewheiss** [comment]
That's bizarre. Can you send me a sample file? 

Is it always 263 lines? Does line length matter? (i.e. maybe it's related to character counts?)

**Comment by andrewheiss** [comment]
So, this isn't actually because of the number of lines, but the number of characters: https://github.com/andrewheiss/SublimeStataEnhanced/issues/34
