### ISSUE TITLE
Error With the Build stata.sublime-build?

### ISSUE THREAD

**Issue by anildoshi** [andrewheiss/SublimeStataEnhanced#36]
Sorry, can't quite figure out this issue I am having. When I try to run my .do file from ST using Cmd-B, I get the following error:
```
osascript: OpenScripting.framework - scripting addition "/Library/ScriptingAdditions/QXPScriptingAdditions.osax" cannot be used with the current OS because it has no OSAXHandlers entry in its Info.plist.
```

I am using ST 3, StataSE 14, and I am running OSX 10.11 if that matters. Any suggestions? Thanks in advanced.

**Comment by andrewheiss** [comment]
That's an extension left by Quark XPress, which apparently affects Applescript systemwide. Try moving or removing the file ([see this for reference](https://discussions.apple.com/thread/7343106?start=0&tstart=0))
