### ISSUE TITLE
Set default Stata version to be executed

### ISSUE THREAD

**Issue by vyky** [andrewheiss/SublimeStataEnhanced#45]
I have multiple version of Stata. How do I set sublime to execute onto certain Stata?

For example if I have Stata 13 and Stata 14. How do I set sublime to send dofile execution to Stata 14, instead of Stata 13?

Currently, it's working when I trashing Stata 13

I'm with OSX

**Comment by andrewheiss** [comment]
Include this in your settings:

    "stata_name": "StataSE"

And make sure that Stata files open in 14 by default instead of 13 (right click on a .do  or .dta file in Finder and change the default program there).
