### ISSUE TITLE
Error trying to parse file

### ISSUE THREAD

**Issue by JarvisBro** [andrewheiss/SublimeStataEnhanced#46]
Hi all, 
After the latest update, I have problem of sending selected line to stata, so I reinstall the package. But when I did so, there's an error message right after I install Stata Enhanced which says: "Error trying to parse file: Trailing comma before closing bracket in ~/Library/Application Support/Sublime Text 2/Packages/SublimeStataEnhanced/Main.sublime-menu:14:17". Can you help explain what I should do.
Many thanks

**Comment by andrewheiss** [comment]
@elbersb Can you maybe take a look at this really quick?

**Comment by elbersb** [comment]
@andrewheiss The comma on line 13 in the file needs to be removed. https://github.com/andrewheiss/SublimeStataEnhanced/blob/master/Main.sublime-menu#L13

**Comment by andrewheiss** [comment]
Awesome, thanks! Fixed!
