### ISSUE TITLE
Use temporary file for line selection

### ISSUE THREAD

**Issue by michaelewens** [andrewheiss/SublimeStataEnhanced#49]
First off, thanks for a great package.  It seems that the newest update -- Mac OSX, Stata MP 14 -- removed the temporary file procedure (i.e. create sublime2stata.do and run).  The "super + enter" now runs the selection line by line and fails to stop in the case of errors.  To test

clear
set more off
di "This will work"
gen test = 1
di "This won't, but things will continue"
gen test2 = max(1)
di "This gets printed even with error above"

The previous tempfile method halted the command if there was an error.  So is there a way to (i) run with the old temp file or (ii) make sure that "super+enter" halts if Stata encounters an r() error?

Edit: perhaps related...now one needs to have "cd directory/of/file" in the selected text (at least once) to work.  Previous versions no longer required it for "super + alt + b".

**Comment by elbersb** [comment]
This seems to be a side effect of the recent change. In general, I think that the AppleScript solution is better, because it is instant and easier to maintain. Unfortunately, there is no way to know whether Stata encountered an error. However, if you send the whole file via Super+B, Stata will stop.

Can you explain the edit more? I don't have a "cd" in my files and it works.

**Comment by michaelewens** [comment]
The Applescript solution does appear to be the best long-term strategy, however, stopping at errors is very useful when sending selections to Stata.  The Super + B works great for errors, but the Super + Enter (i.e. selection) is where things have changed.  Is there a simple way to revert the package to make "send selection to Stata" use the old tempfile?

For the "cd" issue, I just cd into some random directory while in Stata.  Then open up a do file in ST that is not in that directory.  Now select a line like

use "../data/someDTAfile.dta",clear

and hit "Super + Enter" and one gets the error.  This used to not error because the tempfile appears to have automatically cd into the directory where the do file resides.

**Comment by henriqueromero** [comment]
A quick way to revert to temp file command is to change a couple of lines in the text_to_stata.py file. Starting in line 112, there is an if/then statement that that grabs the version of stata and if it's > 13, then it runs selected lines directly to stata, else it creates a temp do file. 
If you change these statements in a way that your version of stata falls within the "else" condition, then you're set. 

E.g. 
```
if sublime.platform() == "osx" and version >= 15:
            cmd = """osascript<< END
                 tell application id "{}"
                    {}
                    DoCommandAsync "do \\\"{}\\\"" with addToReview
                 end tell
                 END""".format(stata_app_id, switch_focus, file_name)
            os.system(cmd)
        elif sublime.platform() == "osx" and version <= 14:
```

You can also revert back to an old version, an exclude the package from package control's auto update. Older versions here https://github.com/andrewheiss/SublimeStataEnhanced/releases

**Comment by michaelewens** [comment]
Thank you, both those issues solved things.  In the future, perhaps a parameter could be added to the setting OSX file with '"useTempFile": "false",' and the line you reference could be

`if sublime.platform() == "osx" and version >= 13 and useTempFile:`

where the default would be useTempFile = false.
