### ISSUE TITLE
running longer scripts

### ISSUE THREAD

**Issue by eborbath** [andrewheiss/SublimeStataEnhanced#50]
Is there an inbuilt limit to the length of the script the package is able to send to stata?
I have a longish script, 2800 lines and if I select all to send, it does not do it, it does not even open stata. If I only select it in parts, it works perfectly well. It's a windows machine.
Any ideas on this?

**Comment by andrewheiss** [comment]
This seems to be similar to #34 but for Windows? The "fix" in #42 was to just give a warning that the selection was too big, since there seems to be no way around AppleScript's character limit. I wonder if Windows has a similar limit?

**Comment by eborbath** [comment]
I realize this is a very novice question, but how do I apply this fix to test if it works?

**Comment by andrewheiss** [comment]
There's not really a fix, per se. The OS X fix just told users to not send big selections. A Windows fix would do the same—we'd just need to find the actual character limit for sending code to Stata and then put a warning saying to not send text that long. 

The only true fix is to not send long code by selecting it, but by running the whole .do file in Stata
