### ISSUE TITLE
Possibility of an Ubuntu version?

### ISSUE THREAD

**Issue by sadatnfs** [andrewheiss/SublimeStataEnhanced#51]
Would be awesome if we could pass codes into an xstata window running in Ubuntu!

**Comment by sadatnfs** [comment]
thoughts?

**Comment by andrewheiss** [comment]
I don't have access to Stata on Linux, so I can't do any development on this. As long as Stata has a way to pass commands to the main window on Linux (similar to the AppleScript API on OS X and the Visual Basic script this package uses for Windows), it should be possible.

**Comment by kylebarron** [comment]
I've written [scripts](https://github.com/kylebarron/stata-autokey) for Linux that use the Autokey automation utility to run your code in a GUI session of Stata. You should only have to change the word "Atom" to "Sublime" in [two](https://github.com/kylebarron/stata-autokey/blob/master/code/run_stata.py#L7) [places](https://github.com/kylebarron/stata-autokey/blob/master/code/run_stata_chunk.py#L8) for it to work in Sublime Text. Then a simple ctrl-r should run your selection in Stata.
