### ISSUE TITLE
OSX: each cmd+d opens a new instance of Stata

### ISSUE THREAD

**Issue by lrdegeest** [andrewheiss/SublimeStataEnhanced#52]
Running ST3 and Stata 13.1. Every time I execute a line of code, the Stata icon in the dock bounces - I assume this means a new instance of Stata is being opened. Is this normal? Seems odd.

**Comment by kylebarron** [comment]
A new instance of Stata is not being opened; that icon bounce is just to tell you that the command has finished running in Stata. You can turn that off by going to Preferences > General Preferences and then uncheck "Notify user when Stata is done".
